{% set name = "prettydiff" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/prettydiff-{{ version }}.tar.gz
  sha256: e0e5ffaa20ee7f8a0295732a954c2fbb2ff37471953f8ab8b0122cbe19497e55

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - prettydiff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python273/prettydiff
  summary: Pretty JSON data diffs
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - liyao001
